

```
#QUESTIONS
```
1.  Display Top 10 Rows of The Dataset
2. Check Last 10 Rows of The Dataset
3. Find Shape of Our Dataset (Number of Rows And Number of Columns)
4.  Getting Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement
5. Check Null Values In The Dataset
6. Drop ID, Notes, Agency, and Status Columns
7. Get Overall Statistics About The Dataframe
8. Find Occurrence of The Employee Names  (Top 5)
9. Find The Number of Unique Job Titles
10.Total Number of Job Titles Contain Captain
11. Display All the Employee Names From Fire Department
12. Find Minimum, Maximum, and Average BasePay
13. Replace 'Not Provided' in EmployeeName' Column to NaN
14. Drop The Rows Having 5 Missing Values
15. Find Job Title of ALBERT PARDINI
16. How Much ALBERT PARDINI Make (Include Benefits)?
17.Display Name of The Person Having The Highest BasePay
18.Find Average BasePay of All Employee Per Year
19. Find Average BasePay of All Employee Per JobTitle
20. Find Average BasePay of Employee Having Job Title ACCOUNTANT  
21. Find Top 5 Most Common Jobs

In [3]:
import pandas as pd

data = pd.read_csv("/content/Salaries.csv",dtype={3:str,4:str,5:str,6:str,12:str})

# 1

data.head(10)


# 2

data.tail(10)

# 3

data.shape

(148654, 13)

In [5]:
#4

data.dtypes

data.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [11]:
#5

data.isnull().any()

#6
data_modified = data.drop(['Id','Notes','Agency','Status'], axis = 1)
data_modified

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014
148650,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014

In [21]:
#7

data.describe()


#8
query = data['EmployeeName'].value_counts()

query.head(5)

#9

query_2 = data['JobTitle'].value_counts()
query_2

#10

query_3 = data[data['JobTitle'].str.contains("Captain")]
query_3

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
36167,36168,John Goldberg,Captain 3,104404.0,0.0,245999.41,24287.23,350403.41,374690.64,2012,NaN,San Francisco,NaN
36180,36181,Michael Rolovich,"Captain, Fire Suppression",145659.03,125868.06,30474.97,45129.03,302002.06,347131.09,2012,NaN,San Francisco,NaN
36184,36185,Darryl Hunter,"Captain, Fire Suppression",145659.03,115673.73,32610.0,49571.51,293942.76,343514.27,2012,NaN,San Francisco,NaN
36186,36187,Michael Delane,"Captain, Fire Suppression",147069.71,113372.94,33012.58,45978.15,293455.23,339433.38,2012,NaN,San Francisco,NaN
36189,36190,Philip Stevens,"Captain, Fire Suppression",124573.5,53895.92,130200.4,28907.03,308669.82,337576.85,2012,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
116604,116605,Gregory L Stewart,"Captain, Fire Suppression",73355.21,18517.18,49917.73,25608.77,141790.12,167398.89,2014,NaN,San Francisco,PT
120867,120868,Michael J Moran,Captain 3,7660.00,1496.09,126560.36,2189.51,135716.45,137905.96,2014,NaN,San Francisco,PT
122361,122362,Michael V Rolovich,"Captain, Fire Suppression",0.00,0.00,130320.75,0.00,130320.75,130320.75,2014,NaN,San Francisco,PT
126588,126589,Stephen M Tittel,Captain 3,68491.89,0.00,23721.91,19020.79,92213.80,111234.59,2014,NaN,San Francisco,PT
132232,132233,Jeanne M Seyler,"Captain, Fire Suppression",61039.43,2285.30,7548.29,20113.76,70873.02,90986.78,2014,NaN,San Francisco,PT

In [39]:
#11

query_4 = data[data['JobTitle'].str.contains("Fire Department")]
query_4['EmployeeName']

#12 , 13 and 14

data.dropna()


data['BasePay'] = data['BasePay'].replace({"Not Provided" :0})

data['BasePay']= pd.to_numeric(data['BasePay'])

print(f"The minimum amount is {data['BasePay'].min()}, the maximum pay is {data['BasePay'].max()} and the average is {data['BasePay'].mean()}")

The minimum amount is -166.01, the maximum pay is 319275.01 and the average is 66323.6568540821

In [42]:
#15
query_5 = data[data['EmployeeName'] == "ALBERT PARDINI"]
query_5

# 16

query_5['TotalPayBenefits']

# 17

data.sort_values('TotalPayBenefits',ascending=False).head(1)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN

In [56]:
#18
data.groupby('Year').agg({'BasePay':pd.Series.mean})

#19
data.groupby('JobTitle').agg({'BasePay':pd.Series.mean})

#20
data1 = data[data['JobTitle'] == "ACCOUNTANT"]
data1.groupby('JobTitle').agg({'BasePay':pd.Series.mean})

#21

abc = data.groupby('JobTitle').agg({'EmployeeName':pd.Series.count})

abc.sort_values('EmployeeName',ascending= False)

                                                    EmployeeName
JobTitle
Transit Operator                                            7036
Special Nurse                                               4389
Registered Nurse                                            3736
Public Svc Aide-Public Works                                2518
Police Officer 3                                            2421
...                                                          ...
EXECUTIVE ASSISTANT TO THE GENERAL MANAGER, RETIRE             1
EXECUTIVE DIRECTOR, SOUTHEAST COMMUNITY FACILITY               1
EXECUTIVE SECRETARY TO THE CONTROLLER                          1
LEGISLATION CLERK                                              1
ZOO CURATOR                                                    1

[2159 rows x 1 columns]